Added 'live' parameter'
expertlead/webflow-php-sdk pull request #7
Opened 2019-07-22 10:13 UTC by Beeld-voerders

Create possibility to work with published items:
- https://developers.webflow.com/#create-new-live-collection-item
- https://developers.webflow.com/#update-live-collection-item

2019-08-07 12:11 UTC, Beeld-voerders commented
Hello @wivern-co-uk,
could you please take a look at my pull request?
thnx, regards,
Haddo Vervest

2019-09-09 18:11 UTC, wivern-co-uk requested changes
Hi @Beeld-voerders, thank you for the fix with `live` parameter. Please fix styling issue, so build is green and we'll release new version right away!

2019-09-11 07:57 UTC, Beeld-voerders commented
@wivern-co-uk All green :-) Please release a new version. Thnx

2019-09-12 21:26 UTC, wivern-co-uk approved these changes

2019-09-12 21:28 UTC, merged